### ISSUE TITLE
Explain difference with Castlemac

### ISSUE THREAD

**Issue by kvaleev** [freetonik/emacs-dotfiles#2]
I think it will be helpful if you highlight in Readme the difference between this repo and your other project—Castlemacs.

Which is the better starting point for an Emacs newbie like me?

**Comment by kvaleev** [comment]
Looks like you have already answered this question:

> Hi all,
> 
> some Emacscast.org listeners said they liked my config. I decided to create a separate setup that follows the same conventions:
> 
> - compatibility with common macOS keybindings
> - respecting Emacs defaults
> - taking advantage of Cmd key
> - providing a simple, minimalist setup suitable for beginners like me

https://www.reddit.com/r/emacs/comments/9hexk6/castlemacs_modern_minimalist_emacs_setup_tailored/

**Comment by freetonik** [comment]
Hey,

yeah, this personal config is way too personal :) Castlemacs was designed specifically to be more useful for other people.
